### ISSUE TITLE
VisDrone evaluation

### ISSUE THREAD

**Issue by caodoanh2001** [cv15nu/mSODANet#1]
Dear authors,

Thanks for you great work. I have a small question:
With VisDrone dataset, we have the special toolkit written in Matlab for evaluating the results. Here is the link: https://github.com/VisDrone/VisDrone2018-DET-toolkit. So, is the results reported in the paper evaluated via this toolkit or COCO API?
Hope that you can clarify this point to me.

**Comment by cv15nu** [comment]
Hello @caodoanh2001 , for "validation" split in the ViSDrone dataset, toolkit was used & for "test" split, since we do not have ground truth annotations, website evaluation was used (http://aiskyeye.com/evaluate/object-detection_2021/). 

Hope this clears any confusion.
